# Generated by Django 4.2 on 2023-05-04 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usercompany",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="resourcesbag",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.project"
            ),
        ),
        migrations.AddField(
            model_name="resourcesbag",
            name="resource_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.resource"
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.project"
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="resource_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.resource"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.category"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="company_nit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.company"
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="company_nit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.company"
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.project"
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="resource_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.resource"
            ),
        ),
        migrations.AddField(
            model_name="announcementproject",
            name="announcement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_projects.announcement",
            ),
        ),
        migrations.AddField(
            model_name="announcementproject",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.project"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_projects.category"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resourcesbag",
            unique_together={("project_id", "resource_id")},
        ),
        migrations.AlterUniqueTogether(
            name="requirement",
            unique_together={("project_id", "resource_id")},
        ),
    ]
